baseUrl = "omalley.dev"
languageCode = "en-ie"
title = "O'Malley.dev"
theme = "PaperMod"

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "rss"

[params]
mainsections = ["posts", "2022-05-06", "2021-03-25", "2020-05-20"]
ShowFullTextinRSS = true
ShowReadingTime = true

[params.homeInfoParams]
Title = "Hi! I'm Scott O'Malley"
Content = "I'm a new Dad, I write code, I love my dog, and I'm attempting to learn Portuguese. (Spelling mistakes are my own)"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[menu.main]]
identifier = "articles"
name = "Articles"
url = "/articles/"
weight = 20
